[build]
  command = "npm run build:tina"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PUBLIC_TINA_CLIENT_ID = "5c6019bf-f1b5-44f6-ac8c-4b1f8c27f74f"
  TINA_TOKEN = "e89d8769739b48b18fcf00fceade75135fccdde9"
  TINA_SEARCH_TOKEN = "6786360139bc1db7ee36f616bdc812115ca890fb"
  SECRETS_SCAN_OMIT_PATHS = "dist/admin/assets/**,public/admin/assets/**,tina/__generated__/**"

# Headers per il CMS admin
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

# Cache control per file di contenuto
[[headers]]
  for = "/src/content/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
